sudo: required
language: python
python:
  - "2.7"

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql_upgrade --force

install:
  - python setup.py develop
  - pip install -r requirements.txt # Install testing packages
  - python setup.py test_settings database externals -s icat  # Only install external icat as nothing else is required


script:
  # ================ Assert Test Setup =============== #
  - nosetests build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./build/tests/test_pylint.sh

  # ================ Nose unit tests ================ #

  # Utils tests
  - nosetests utils/clients/tests
