sudo: required
language: python
python:
  - "2.7"

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql_upgrade --force
<<<<<<< HEAD
  - sudo service mysql restart

install:
  - python setup.py develop
  - pip install -r requirements.txt # Install testing packages
  - python setup.py test_settings
  - sudo python setup.py externals -s activemq,icat # Mantid not yet required`
  - sudo python setup.py start
  - python setup.py database

script:
  # ================ Assert Test Setup =============== #
  - nosetests build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./build/tests/test_pylint.sh
=======
  - mysql < scripts/Build/database/travis-db-setup.sql

install:
  - python setup.py install
  - pip install -r requirements.txt
  - ./scripts/Build/install/icat.sh
  - ./scripts/Build/install/activemq.sh

script:
  # ================== Test setup ==================== #
  - ./scripts/Build/project/migrate_test_settings.sh
  - ./scripts/Build/database/generate_testing_database.sh
  - mysql < scripts/Build/database/populate-reduction_viewer-db.sql

  # ================ Assert Test Setup =============== #
  - nosetests scripts/Build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./scripts/Build/tests/test_pylint.sh
>>>>>>> origin/develop

  # ================ Nose unit tests ================ #

  # Utils tests
  - nosetests utils/clients/tests
  - nosetests WebApp/autoreduce_webapp/tests
