language: python
python:
  - "2.7"

install:
  - pip install nose
  - pip install stomp.py
  # ActiveMQ install
  - wget "http://www.apache.org/dyn/closer.cgi?filename=/activemq/5.15.3/apache-activemq-5.15.3-bin.tar.gz&action=download" -O apache-activemq-5.15.3-bin.tar.gz
  - sudo tar xvf apache-activemq-5.15.3-bin.tar.gz
  - sudo chmod 755 apache-activemq-5.15.3/bin/activemq
  - sudo ./apache-activemq-5.15.3/bin/activemq start
  - sleep 5
  - sudo netstat -anpt

# command to run tests
script:
  - nosetests Scripts/Build/test/test_activemq.py
