sudo: required
language: python
python:
  - "3.7"

services:
  - mysql

dist: xenial

before_install:
  - mysql_upgrade --force
  - sudo service mysql restart
  # Need to do this first time
  - mysql < build/database/reset_autoreduction_db.sql

install:
  # Install autoreduction
  - pip3 install -e .
  # Install test suite dependencies
  - pip3 install -r requirements.txt

  # ================== setup test environment ==================== #
  - python3 setup.py test_settings
  # Externals must be after test_settings
  - python3 setup.py externals -s activemq
  - python3 setup.py database
  - cat build.log
  - _LOCAL_PYTHON_PATH=$(which python3)
  - sudo $_LOCAL_PYTHON_PATH setup.py start

script:
  - py.test build/tests/test_db_generation.py  # perform initial check of database
  # ================ Functional tests =============== #
  - echo "Running Unit tests"
  # `-p no:django` disables the django plugin for tests outside the web app!
  # `--ignore=WebApp` ignores the web app directory so it's tests aren't ran
  - >
    py.test -p no:django --ignore=systemtests --ignore=WebApp
    --cov=build --cov=monitors --cov=queue_processors --cov=scripts
    --cov=utils --cov=docker_reduction --cov=paths --cov=plotting --cov=model

  # Tests the web app separately as that requries setting up a custom settings.py file
  - py.test WebApp/autoreduce_webapp --cov-append --cov=WebApp/autoreduce_webapp
  - echo "Running System Tests"
  - py.test systemtests --cov-append

  # ================ Static Analysis ================= #
  # ToDo: These should all be collapsed into one once autoreduction gets a single code package
  - pylint build
  - pylint docker_reduction
  - pylint model
  - pylint monitors
  - pylint queue_processors
  - pylint scripts
  - pylint systemtests
  - pylint utils
  - pylint plotting

after_success:
  - coveralls
