language: python
python:
  - "2.7"

install:
  - pip install pylint

# command to run tests
script:
  # =============Pylint commands============= #
  - pylint EndOfRunMonitor
  - pylint Scripts/ActiveMQTests
  - pylint Scripts/ManualSubmissionScript
  - pylint Scripts/NagiosChecks
  - QueueProcessors
  - WebApp/autoreduce_webapp/autoreduce_webapp/
