language: python
python:
  - "2.7"

install:
  # ========== Project dependecies ========== #
  - pip install django
  - pip install mysql-python
  - pip install python-daemon
  - pip install requests
  - pip install stomp.py
  - pip install suds
  - pip install SQLAlchemy
  - pip install watchdog
  # === ICAT === #
  - wget https://icatproject.org/misc/python-icat/download/python-icat-0.13.1.tar.gz
  - sudo tar xvf python-icat-0.13.1.tar.gz
  - cd python-icat-0.13.1
  - py_path=$(which python)
  - sudo $py_path setup.py build
  - sudo $py_path setup.py install
  - cd ..
  - ls /usr/local/lib/python2.7/dist-packages/
  - python -c "help('modules')"
  - python -c "help('modules')"
  # ======== Analysis/Testing tools ========= #
  - pip install pylint

# command to run tests
script:
  # =============Pylint commands============= #
  # Run pylint without check for C0103 (invalid-name) as this triggers on module names
  # There is currently no work around for this - we should change module names to lower case
  - pylint -d C0103 EndOfRunMonitor

  - pylint -d C0103 Scripts/ActiveMQTests/sendMessage.py
  - pylint -d C0103 Scripts/ActiveMQTests/stompActiveMQtest.py
  - pylint -d C0103 Scripts/ManualSubmissionScript
  - pylint -d C0103 Scripts/NagiosChecks/autoreduce_checklastrun.py

  - pylint -d C0103,W0403,W0141,R0401 QueueProcessors/QueueProcessor

  - pylint -d C0103 WebApp/autoreduce_webapp/autoreduce_webapp/
