coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        branches:
          - master
        if_ci_failed: error
        informational: false
        only_pulls: false
        require_ci_to_pass: no