name: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Verify MySQL connection from host
      run: |
        apt-get update && apt-get install -y mysql-server mysql-client
        mysql --host autoreduction_db --port 3306 -u root -e "SHOW DATABASES"
      shell: bash

    - name: Set up database
      run: mysql --host autoreduction_db --port 3306 -u root < build/database/reset_autoreduction_db.sql
      shell: bash

    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Setup test environment
      run: |
        python setup.py test_settings
        # Externals must be after test_settings
        python setup.py externals -s activemq
        python setup.py database
        cat build.log
        _LOCAL_PYTHON_PATH=$(which python)
        $_LOCAL_PYTHON_PATH setup.py start
      shell: bash
