name: Build Autoreduction
description: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Setup Docker MySQL
      shell: bash
      run: |
        docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
        -e MYSQL_USER=test-user \
        -e MYSQL_PASSWORD=pass \
        -e MYSQL_DATABASE=autoreduction \
        --name=autoreduction_db \
        --network=host \
        -dit mysql:5.7
        grep -m 1 "Test database successfully initialised" < $(docker logs --follow autoreduction_db)

    - name: Verify MySQL connection from host
      shell: bash
      run: |
        mysql --host 127.0.0.1 --port 3306 -u root -e "SHOW DATABASES"

    - name: Set up database
      shell: bash
      run: mysql --host 127.0.0.1 --port 3306 -u root < build/database/reset_autoreduction_db.sql

    - name: Install Autoreduction
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install test suite dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Setup test environment
      shell: bash
      run: |
        python setup.py test_settings
        # Externals must be after test_settings
        python setup.py externals -s activemq
        python setup.py database
        cat build.log
        _LOCAL_PYTHON_PATH=$(which python)
        $_LOCAL_PYTHON_PATH setup.py start
