name: 'Build Autoreduction in a test enviroment'
description: 'Intial steps to build Autoreduction in a test enviroment'
runs:
  using: "composite"
  steps:       
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -u root -e "SHOW DATABASES"
      shell: bash

    - name: Set up database
      run: mysql --host 127.0.0.1 --port 3306 -u root < build/database/reset_autoreduction_db.sql
      shell: bash

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip3 install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip3 install -r requirements.txt
      shell: bash

    - name: Setup test environment
      run: |
        python3 setup.py test_settings
        # Externals must be after test_settings
        python3 setup.py externals -s activemq
        python3 setup.py database
        cat build.log
        _LOCAL_PYTHON_PATH=$(which python3)
        sudo $_LOCAL_PYTHON_PATH setup.py start
      shell: bash
