name: Selenium - Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: test-user
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: autoreduction
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: ./.github/actions/build-autoreduction

      - name: Perform initial check of database
        run: py.test build/tests/test_db_generation.py

      - name: Run Django server
        run: |
          python3 WebApp/autoreduce_webapp/manage.py runserver &
          sleep 10

      - name: Run selenium Tests
        run: |
          mv webtests/config.json.example webtests/config.json
          python3 -m webtests.runner --headless
