# This is a basic workflow to help you get started with Actions

name: Testing on Ubuntu 18 (Xenial)

on: 
  push:
  pull_request:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql -u root -e "SHOW DATABASES"
      
      - name: Set up database
        run: |
          mysql_upgrade --force
          sudo service mysql restart
          # Need to do this first time
          mysql < build/database/reset_autoreduction_db.sql
      
      - name: Install Autoreduction
        run: |
          python -m pip install --upgrade pip
          pip3 install -e .
      
      - name: Install test suite dependencies
        run: pip3 install -r requirements.txt
